httpPort: 13000
metricPort: 5856
appName: connector
log:
  level: DEBUG
db:
  mongo:
    url: mongodb://192.168.31.208:12606
    userName: misa
    password: 86c15220
    minPoolSize: 10
    maxPoolSize: 100
    db: msqp
  redis:
    addr: 192.168.31.208:12616
    poolSize: 10
    minIdleConns: 1
    password:
jwt:
  secret: 123456
  exp: 7
domain:
  user:
    name: user/v1
    loadBalance: true
etcd:
  addrs:
    - 192.168.31.208:12624
  rwTimeout: 3
  dialTimeout: 3
services:
  connector:
    id: connector-1
    clientHost: 127.0.0.1
    clientPort: 12000